version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "5000:80"
    networks:
      - todo-list
    volumes:
      - "/home/infomach/todo_list/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/home/infomach/todo_list/content:/usr/share/nginx/html:ro"
    environment:
      NGINX_HOST: 192.168.1.197
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  api:
    image: todolist-api:latest
    ports:
      - "5001:5000"
    networks:
      - todo-list
    secrets:
      - root_password
    environment:
      MYSQL_DB_URL: jdbc:mysql://db:3306/todo_list?useTimezone=true&serverTimezone=America/Sao_Paulo
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD_FILE: /run/secrets/root_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  db:
    image: mysql:8
    ports:
      - "5002:3306"
      - "5003:33060"
    networks:
      - todo-list
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_storage:/var/lib/mysql"
    secrets:
      - root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
      MYSQL_DATABASE: todo_list
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

volumes:
  mysql_storage:

secrets:
  root_password:
    file: ./mysql_root.txt

networks:
  todo-list:
    driver: overlay
    name: todo-list
