version: '3.7'

services:
  nginx:
    image: nginx
    ports: 
      - "80:80"
    deploy:
      replicas: 2
  
  visualizer:
    image: dockersamples/visualizer
    ports: 
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      